apiVersion: apps/v1
kind: Deployment
metadata:
  name: vetsservice-deployment
  namespace: petclinic
  labels:
    app: vetsservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vetsservice
  template:
    metadata:
      labels:
        app: vetsservice
    spec:
      containers:
        - name: vetsservice
          image: caannamalai/vetsservice:3.2.4
          ports:
            - containerPort: 8082

---

apiVersion: v1
kind: Service
metadata:
  name: vetsservice-service
  namespace: petclinic
  labels:
    app: vetsservice
spec:
  selector:
    app: vetsservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vetsservice-ingress
  namespace: petclinic
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host:  ""
      http:
        paths:
          - path: /api/vet
            pathType: Prefix
            backend:
              service:
                name: vetsservice-service
                port:
                  number: 80
