apiVersion: apps/v1
kind: Deployment
metadata:
  name: vetsservice-deployment
  namespace: ashok
  labels:
    app: vetsservice
spec:
  replicas: 1  # Number of replicas
  selector:
    matchLabels:
      app: vetsservice
  template:
    metadata:
      labels:
        app: vetsservice
    spec:
      containers:
        - name: vetsservice
          image: caannamalai/vets-service:3.2.4  
          ports:
            - containerPort: 8082  
          readinessProbe: 
            httpGet:
              path: /actuator/health  
              port: 8082
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe: 
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 30

---

apiVersion: v1
kind: Service
metadata:
  name: vetsservice-service
  namespace: ashok
  labels:
    app: vetsservice
spec:
  type: LoadBalancer  
  selector:
    app: vetsservice
  ports:
    - protocol: TCP
      port: 8082       
      targetPort: 8082  
  sessionAffinity: None  
