apiVersion: apps/v1
kind: Deployment
metadata:
  name: vets-service-deployment
  namespace: ashok
  labels:
    app: vets-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vets-service
  template:
    metadata:
      labels:
        app: vets-service
    spec:
      containers:
        - name: vets-service
          image: caannamalai/vets-service:3.2.4
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: vets-service
  namespace: ashok
  labels:
    app: vets-service
spec:
  type: LoadBalancer
  ports:
    - port: 8082
      targetPort: 8082
  selector:
    app: vets-service
