spring:
  application:
    name: vets-service
  config:
    import: 
      - optional:configserver:${CONFIG_SERVER_URL:http://34.122.225.157:8888/}
  cache:
    cache-names: vets
  profiles:
    active: production

eureka:
  instance:
    # Register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${random.uuid}

vets:
  cache:
    ttl: 60
    heap-size: 100

server:
  port: 8083

---
spring:
  config:
    activate:
      on-profile: default

eureka:
  client:
    serviceUrl:
      defaultZone: http://35.239.105.95:8761/

---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://34.122.225.157:8888/
  zipkin:
    baseUrl: http://tracing-server:9411
