spring:
  application:
    name: vets-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://34.122.225.157:8888/}
  cache:
    cache-names: vets
  profiles:
    active: production
server:
  port: 8083 
eureka:
  client:
    service-url:
      defaultZone: http://35.239.105.95:8761/eureka/  
    instance:
      prefer-ip-address: true  
spring:
  application:
    name: vets-service 

---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://34.122.225.157:8888/
