spring:
  application:
    name: vets-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://34.28.103.87:8888/}
  cache:
    cache-names: vets
  profiles:
    active: production
server: 
  port: 8082

---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://34.28.103.87:8888/
