spring:
  application:
    name: vets-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
  cache:
    cache-names: vets
  profiles:
    active: production

---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888
﻿vets:
  cache:
    ttl: 60
    heap-size: 100

---
spring:
  config:
    activate:
      on-profile: default
eureka:
  instance:
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${random.uuid}

---
spring:
  config:
    activate:
      on-profile: docker
  zipkin:
    baseUrl: http://tracing-server:9411
server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
